Repository hash-checker/hash-checker, pull requests merged in 2021-07, with the labels that each got.

#133 2021-06-18 v. 3.6.6: including pt-BR translation
  app/src/main/java/com/smlnskgmail/jaman/hashchecker/logic/locale/api/Language.java
  app/src/main/res/values-pt-BR/strings.xml
Labels: translation

#134 2021-07-04 v. 3.6.6: added @itamarc to Contributors and updated docs
  README.md
Labels: documentation

#130 2021-05-31 v. 3.6.6: added in-app update feature
  app/build.gradle
  app/src/main/java/com/smlnskgmail/jaman/hashchecker/MainActivity.java
Labels: feature

#135 2021-07-04 v. 3.6.6: added @vipozdn to Contributors
  README.md
Labels: documentation

#137 2021-07-04 v. 3.6.6: updated Contributors list
  README.md
Labels: documentation

#138 3.6.6 pt-rBR locale fix
  app/src/main/java/com/smlnskgmail/jaman/hashchecker/logic/locale/api/Language.java
  app/src/main/res/values-pt-rBR/strings.xml
Labels: translation
