Repository hash-checker/hash-checker, pull requests merged in 2023-06, with the labels that each got.

#190 Fix wrong return value for getHashType() in SHA3 tests
  app/src/androidTest/java/com/smlnskgmail/jaman/hashchecker/calculator/jdk/sha3/SHA3256JdkHashCalculatorTest.java
  app/src/androidTest/java/com/smlnskgmail/jaman/hashchecker/calculator/jdk/sha3/SHA3384JdkHashCalculatorTest.java
  app/src/androidTest/java/com/smlnskgmail/jaman/hashchecker/calculator/jdk/sha3/SHA3512JdkHashCalculatorTest.java
  app/src/main/java/com/smlnskgmail/jaman/hashchecker/components/settings/impl/SharedPreferencesSettings.java
  app/src/main/java/com/smlnskgmail/jaman/hashchecker/features/settings/view/lists/weblinks/WebLink.java
Labels: bug, test

#192 2023-02-11 v. 3.6.9-1: added @elliotwutingfeng to Contributors List
  README.md
Labels: documentation

#193 2023-06-14 v. 3.6.9-1: added GitHub downloads count to README.md
  README.md
Labels: documentation

#194 2023-06-14 v. 3.6.9-1: updated README.md
  README.md
Labels: documentation

#196 2023-06-18 v. 3.6.9-1: added @Abhisht01 to Contributors List
  README.md
Labels: documentation

#198 2023-06-24 v. 3.6.9: closed #191
  .github/workflows/build.yml
  README.md
  app/build.gradle
  app/src/androidTest/java/com/smlnskgmail/jaman/hashchecker/calculator/GenerateHashFromTextTest.java
  app/src/androidTest/java/com/smlnskgmail/jaman/hashchecker/rateapp/RateAppDialogTest.java
  app/src/androidTest/java/com/smlnskgmail/jaman/hashchecker/settings/BaseSettingsTest.java
  app/src/androidTest/java/com/smlnskgmail/jaman/hashchecker/ui/BaseUITest.java
  app/src/main/java/com/smlnskgmail/jaman/hashchecker/components/locale/api/Language.java
  app/src/main/res/values-hi/strings.xml
Labels: translation, test

#200 2023-06-24 v. 3.6.9: fixed README.md
  README.md
Labels: documentation

#197 2023-06-20 Added: feature to gen hash from folder.
  README.md
  app/src/androidTest/java/com/smlnskgmail/jaman/hashchecker/calculator/HashCalculatorTaskExceptionTest.java
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/smlnskgmail/jaman/hashchecker/App.java
  app/src/main/java/com/smlnskgmail/jaman/hashchecker/components/hashcalculator/api/HashCalculator.java
  app/src/main/java/com/smlnskgmail/jaman/hashchecker/components/hashcalculator/api/HashCalculatorTask.java
  app/src/main/java/com/smlnskgmail/jaman/hashchecker/components/hashcalculator/jdk/JdkHashCalculator.java
  app/src/main/java/com/smlnskgmail/jaman/hashchecker/features/hashcalculator/HashCalculatorFragment.java
  app/src/main/java/com/smlnskgmail/jaman/hashchecker/features/hashcalculator/lists/actions/Action.java
  app/src/main/java/com/smlnskgmail/jaman/hashchecker/features/hashcalculator/lists/actions/types/UserActionType.java
  app/src/main/java/com/smlnskgmail/jaman/hashchecker/features/hashcalculator/lists/actions/ui/SourceSelectActionsBottomSheet.java
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fa/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hi/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-iw/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-no/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-vi/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values/strings.xml
Labels: feature

#202 2023-06-25 v. 3.6.9: updated some GitHub stuff
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/pull_request_template.md
  .github/workflows/release.yml
Labels: documentation

#203 2023-06-25 v. 3.6.9: closed #201
  README.md
Labels: translation, documentation

#204 2023-06-25 v. 3.6.9: updated README.md
  README.md
Labels: documentation

#206 2023-06-25 v. 3.6.9: updated README.md
  README.md
Labels: documentation

#205 2023-06-25 v. 3.7.0: closed #199
  app/build.gradle
  app/src/googlePlay/java/com/smlnskgmail/jaman/hashchecker/MainActivity.java
  app/src/main/java/com/smlnskgmail/jaman/hashchecker/App.java
  app/src/main/res/drawable-v26/ic_shortcut_folder.xml
  app/src/main/res/drawable-v26/ic_shortcut_from_folder.xml
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: bug, release

#208 2023-06-25 v. 3.7.0: increased version code
  app/build.gradle
Labels: bug, release

#210 2023-06-27 Added: feature to remove the clipboard.
  app/src/main/java/com/smlnskgmail/jaman/hashchecker/components/clipboard/Clipboard.java
Labels: feature

#213 2023-06-29 v. 3.7.0: updated docs
  README.md
Labels: documentation

#214 2023-06-29 v. 3.7.0: updated docs
  README.md
Labels: documentation

#215 2023-06-29 v. 3.7.0: added auto assign to CI
  .github/workflows/auto-assign.yml
Labels: ci

#216 2023-06-29 v. 3.7.0: added Codecov config
  codecov.yaml
Labels: code format

#218 2023-06-29 v. 3.7.0: updated Contributors
  README.md
Labels: documentation

#217 2023-06-29 Update: Readme.md with Burmese lang.
  README.md
Labels: documentation

#219 2023-06-29 v. 3.7.0: rearranged Contributors
  README.md
Labels: documentation

#220 2023-06-29 v. 3.7.0: increased screenshots size in README
  README.md
Labels: documentation

#221 2023-06-29 v. 3.7.0: fixed screenshots size
  README.md
Labels: documentation

#222 2023-06-29 v. 3.7.0: fixed screenshots size
  README.md
Labels: documentation

#223 2023-06-29 v. 3.7.0: updated Codecov config
  codecov.yaml
Labels: code format
