Repository hash-checker/hash-checker, pull requests merged in 2023-07, with the labels that each got.

#226 2023-07-01 v. 3.7.1: closed #174
  app/build.gradle
  app/src/main/java/com/smlnskgmail/jaman/hashchecker/components/locale/api/Language.java
  app/src/main/java/com/smlnskgmail/jaman/hashchecker/components/locale/impl/LanguageConfigImpl.java
Labels: bug

#212 3.7.1
  README.md
  app/build.gradle
  app/src/main/java/com/smlnskgmail/jaman/hashchecker/components/clipboard/Clipboard.java
  app/src/main/java/com/smlnskgmail/jaman/hashchecker/components/locale/api/Language.java
  app/src/main/res/values-my/strings.xml
Labels: release

#228 2023-07-18 v. 3.7.1: updated app and code versions
  app/build.gradle
Labels: release

#229 Docs
  README.md
Labels: translation, documentation

#230 2023-07-20 Added: Blake2b Hashing Algo
  app/src/androidTest/java/com/smlnskgmail/jaman/hashchecker/calculator/jdk/blake2b/Blake2bJdkHashCalculatorTest.java
  app/src/main/java/com/smlnskgmail/jaman/hashchecker/components/hashcalculator/api/HashType.java
  app/src/main/java/com/smlnskgmail/jaman/hashchecker/components/hashcalculator/hash/Blake2B.java
  app/src/main/java/com/smlnskgmail/jaman/hashchecker/components/hashcalculator/hash/Constants.java
  app/src/main/java/com/smlnskgmail/jaman/hashchecker/components/hashcalculator/jdk/JdkHashCalculatorDigest.java
  app/src/test/java/com/smlnskgmail/jaman/hashchecker/calculator/HashTypeTest.java
  app/src/test/java/com/smlnskgmail/jaman/hashchecker/calculator/jdk/JdkHashCalculatorDigestTest.java
  app/src/test/java/com/smlnskgmail/jaman/hashchecker/calculator/jdk/JdkHashCalculatorTest.java
Labels: feature

#234 2023-07-24 Added: FNV-1A Algorithm.
  app/src/androidTest/java/com/smlnskgmail/jaman/hashchecker/calculator/jdk/fnv1a/FNV1A1024HashCalculatorTest.java
  app/src/androidTest/java/com/smlnskgmail/jaman/hashchecker/calculator/jdk/fnv1a/FNV1A128HashCalculatorTest.java
  app/src/androidTest/java/com/smlnskgmail/jaman/hashchecker/calculator/jdk/fnv1a/FNV1A256HashCalculatorTest.java
  app/src/androidTest/java/com/smlnskgmail/jaman/hashchecker/calculator/jdk/fnv1a/FNV1A32HashCalculatorTest.java
  app/src/androidTest/java/com/smlnskgmail/jaman/hashchecker/calculator/jdk/fnv1a/FNV1A512HashCalculatorTest.java
  app/src/androidTest/java/com/smlnskgmail/jaman/hashchecker/calculator/jdk/fnv1a/FNV1A64HashCalculatorTest.java
  app/src/main/java/com/smlnskgmail/jaman/hashchecker/components/hashcalculator/api/HashType.java
  app/src/main/java/com/smlnskgmail/jaman/hashchecker/components/hashcalculator/hash/Constants.java
  app/src/main/java/com/smlnskgmail/jaman/hashchecker/components/hashcalculator/hash/FNV1a.java
  app/src/main/java/com/smlnskgmail/jaman/hashchecker/components/hashcalculator/hash/HashConstants.java
  app/src/main/java/com/smlnskgmail/jaman/hashchecker/components/hashcalculator/jdk/JdkHashCalculatorDigest.java
  app/src/test/java/com/smlnskgmail/jaman/hashchecker/calculator/HashTypeTest.java
  app/src/test/java/com/smlnskgmail/jaman/hashchecker/calculator/jdk/JdkHashCalculatorDigestTest.java
  app/src/test/java/com/smlnskgmail/jaman/hashchecker/calculator/jdk/JdkHashCalculatorTest.java
Labels: feature

#238 3.7.2 refactoring
  app/checkstyle.gradle
  app/src/androidTest/java/com/smlnskgmail/jaman/hashchecker/calculator/jdk/blake2b/Blake2bJdkHashCalculatorTest.java
  app/src/main/java/com/smlnskgmail/jaman/hashchecker/components/hashcalculator/api/HashCalculatorTask.java
  app/src/main/java/com/smlnskgmail/jaman/hashchecker/components/hashcalculator/hash/Blake2B.java
  app/src/main/java/com/smlnskgmail/jaman/hashchecker/components/hashcalculator/hash/FNV1a.java
  app/src/main/java/com/smlnskgmail/jaman/hashchecker/components/hashcalculator/hash/HashConstants.java
  app/src/main/java/com/smlnskgmail/jaman/hashchecker/components/hashcalculator/jdk/JdkHashCalculator.java
  app/src/main/java/com/smlnskgmail/jaman/hashchecker/components/hashcalculator/jdk/JdkHashCalculatorDigest.java
  app/src/main/java/com/smlnskgmail/jaman/hashchecker/components/locale/impl/LanguageConfigImpl.java
  app/src/main/java/com/smlnskgmail/jaman/hashchecker/features/hashcalculator/HashCalculatorFragment.java
  app/src/test/java/com/smlnskgmail/jaman/hashchecker/calculator/jdk/JdkHashCalculatorTest.java
Labels: code format

#239 232
  .github/workflows/build.yml
  app/build.gradle
  app/src/main/java/com/smlnskgmail/jaman/hashchecker/components/hashcalculator/hash/Blake2B.java
Labels: bug, ci

#240 2023-07-30 v. 3.7.2: updated tests
  app/build.gradle
  app/src/androidTest/java/com/smlnskgmail/jaman/hashchecker/AndroidTestSuite.java
  app/src/androidTest/java/com/smlnskgmail/jaman/hashchecker/settings/HashValueInLowerCaseTest.java
  app/src/main/java/com/smlnskgmail/jaman/hashchecker/features/hashcalculator/HashCalculatorFragment.java
Labels: test

#241 3.7.2 GitHub actions update
  .github/workflows/auto-assign.yml
  .github/workflows/build.yml
  app/build.gradle
  app/checkstyle.gradle
  app/src/androidTest/java/com/smlnskgmail/jaman/hashchecker/AndroidTestSuite.java
  app/src/androidTest/java/com/smlnskgmail/jaman/hashchecker/calculator/jdk/blake2b/Blake2bJdkHashCalculatorTest.java
  app/src/androidTest/java/com/smlnskgmail/jaman/hashchecker/calculator/jdk/fnv1a/FNV1A1024HashCalculatorTest.java
  app/src/androidTest/java/com/smlnskgmail/jaman/hashchecker/calculator/jdk/fnv1a/FNV1A128HashCalculatorTest.java
  app/src/androidTest/java/com/smlnskgmail/jaman/hashchecker/calculator/jdk/fnv1a/FNV1A256HashCalculatorTest.java
  app/src/androidTest/java/com/smlnskgmail/jaman/hashchecker/calculator/jdk/fnv1a/FNV1A32HashCalculatorTest.java
  app/src/androidTest/java/com/smlnskgmail/jaman/hashchecker/calculator/jdk/fnv1a/FNV1A512HashCalculatorTest.java
  app/src/androidTest/java/com/smlnskgmail/jaman/hashchecker/calculator/jdk/fnv1a/FNV1A64HashCalculatorTest.java
  app/src/androidTest/java/com/smlnskgmail/jaman/hashchecker/settings/HashValueInLowerCaseTest.java
  app/src/main/java/com/smlnskgmail/jaman/hashchecker/components/hashcalculator/api/HashCalculatorTask.java
  app/src/main/java/com/smlnskgmail/jaman/hashchecker/components/hashcalculator/api/HashType.java
  app/src/main/java/com/smlnskgmail/jaman/hashchecker/components/hashcalculator/hash/Blake2B.java
  app/src/main/java/com/smlnskgmail/jaman/hashchecker/components/hashcalculator/hash/FNV1a.java
  app/src/main/java/com/smlnskgmail/jaman/hashchecker/components/hashcalculator/hash/HashConstants.java
  app/src/main/java/com/smlnskgmail/jaman/hashchecker/components/hashcalculator/jdk/JdkHashCalculator.java
  app/src/main/java/com/smlnskgmail/jaman/hashchecker/components/hashcalculator/jdk/JdkHashCalculatorDigest.java
  app/src/main/java/com/smlnskgmail/jaman/hashchecker/components/locale/impl/LanguageConfigImpl.java
  app/src/main/java/com/smlnskgmail/jaman/hashchecker/features/hashcalculator/HashCalculatorFragment.java
  app/src/test/java/com/smlnskgmail/jaman/hashchecker/calculator/HashTypeTest.java
  app/src/test/java/com/smlnskgmail/jaman/hashchecker/calculator/jdk/JdkHashCalculatorDigestTest.java
  app/src/test/java/com/smlnskgmail/jaman/hashchecker/calculator/jdk/JdkHashCalculatorTest.java
Labels: ci

#242 2023-07-30 v. 3.7.2: fixed CI pipeline
  app/build.gradle
Labels: ci

#244 2023-07-30 v. 3.7.2: updated app version and code version
  app/build.gradle
Labels: bug

#246 2023-07-30 v. 3.7.2: updated README.md
  README.md
Labels: documentation
