Repository hash-checker/hash-checker, pull requests merged in 2023-08, with the labels that each got.

#254 2023-08-01 v. 3.7.3: closed #253
  app/build.gradle
Labels: release

#256 248
  app/build.gradle
  app/src/main/res/values/strings-non-translatable.xml
Labels: bug

#255 3.7.3
  app/build.gradle
Labels: release

#257 2023-08-01 v. 3.7.3: closed #247
  app/src/main/java/com/smlnskgmail/jaman/hashchecker/features/settings/view/SettingsFragment.java
Labels: bug

#259 2023-08-01 v. 3.7.3: closed #249
  app/src/main/AndroidManifest.xml
Labels: feature

#265 2023-08-02 v. 3.7.3: closed #252
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/smlnskgmail/jaman/hashchecker/features/settings/view/lists/weblinks/WebLink.java
  app/src/main/res/drawable/ic_linkedin.xml
  app/src/main/res/drawable/ic_rubygems.xml
  app/src/main/res/drawable/ic_stack_oveflow.xml
  app/src/main/res/drawable/ic_twitter.xml
  app/src/main/res/values/strings-non-translatable.xml
Labels: feature

#268 261
  app/src/main/java/com/smlnskgmail/jaman/hashchecker/components/hashcalculator/hash/Blake2B.java
  app/src/main/java/com/smlnskgmail/jaman/hashchecker/components/hashcalculator/hash/FNV1a.java
  app/src/main/java/com/smlnskgmail/jaman/hashchecker/components/hashcalculator/jdk/JdkHashCalculator.java
  app/src/main/java/com/smlnskgmail/jaman/hashchecker/components/hashcalculator/jdk/JdkHashCalculatorDigest.java
  app/src/main/java/com/smlnskgmail/jaman/hashchecker/features/hashcalculator/HashCalculatorFragment.java
Labels: code format

#269 2023-08-02 v. 3.7.3: closed #267
  .github/workflows/build.yml
Labels: ci

#273 2023-08-02 v. 3.7.3: closed #272
  README.md
  media/banners/bn_amanzon_appsore.png
Labels: documentation

#274 272 fix
  media/banners/bn_amazon_appsore.png
Labels: bug, documentation

#275 272 fix 2
  README.md
  media/banners/bn_amazon_appstore.png
Labels: documentation

#276 2023:08:16 Added: Webview for Privacy Policy.
  app/src/debug/AndroidManifest.xml
  app/src/main/java/com/smlnskgmail/jaman/hashchecker/di/components/AppComponent.java
  app/src/main/java/com/smlnskgmail/jaman/hashchecker/features/settings/view/lists/weblinks/WebLinksBottomSheet.java
  app/src/main/java/com/smlnskgmail/jaman/hashchecker/features/settings/view/lists/weblinks/WebLinksListAdapter.java
  app/src/main/java/com/smlnskgmail/jaman/hashchecker/features/webview/WebFragment.java
  app/src/main/res/layout/web_view.xml
  app/src/main/res/menu/menu_webview.xml
Labels: feature
